"""The AppDir ``AppRun`` launcher — a POSIX shell script (linux-spec).

AppImage does not require an ELF ``AppRun``, and Linux has no analog of the
Finder/LaunchServices problem that forced the compiled Mach-O stub on macOS, so
the launcher is a small shell script. It resolves its own directory (so the
AppDir stays relocatable), points the bundled CPython at its own home + the
app's ``lib``/``app`` directories, sets the SDL WM_CLASS so the window groups
under the ``.desktop``'s ``StartupWMClass``, and ``exec``s the interpreter on
the entry-point module.

By default there is deliberately **no ``LD_LIBRARY_PATH``**: PBS rpaths are
``$ORIGIN``-relative and manylinux wheels vendor their own native libs
(auditwheel), so the host's libGL/libEGL are found on the normal loader path.
The one exception is when the app declares ``[tool.kivy.linux.native.binaries]``:
then ``usr/bin`` is *prepended* to ``PATH`` (helpers win by name) and *appended*
to ``LD_LIBRARY_PATH`` (declared libs load by soname but never shadow the host's
or the wheels' own ``.so``s — decided Option B in linux-spec). The
PATH-prepend / LD_LIBRARY_PATH-append asymmetry is deliberate: declared tools
win; declared libs never shadow the host.
"""

from __future__ import annotations

import keyword
from pathlib import Path

from . import AppDirError

# ``{entry}`` is a dotted module name (validated as such below); ``{app_id}`` is
# a validated ``.desktop`` basename (letters/digits/hyphen/period) — both safe
# to inline.
#
# The entry point is run with ``-m`` rather than by path, which is what makes
# the launcher independent of ``strip_source``. Exec'ing ``usr/app/{entry}.py``
# shipped a release AppImage that could not start at all: ``package`` applies
# ``strip_source`` by default, which leaves ``main.pyc`` and deletes the
# ``main.py`` AppRun was still naming, so the interpreter exited 2 before Python
# came up. ``-m`` goes through the import system, which loads a sourceless
# ``.pyc`` in the legacy layout exactly as happily as a ``.py`` — so the payload
# can change shape without the launcher having to be told.
#
# ``-P`` is load-bearing, not decoration. Plain ``-m`` puts the *current working
# directory* on ``sys.path``, which exec'ing a script never did (that put the
# script's own directory there), so adopting ``-m`` without it would let any
# directory a user happens to launch from shadow a stdlib or app module. ``-P``
# restores the old behaviour: ``sys.path`` comes from ``PYTHONPATH`` above and
# nothing else. It needs CPython >= 3.11, which every runtime PBS ships for the
# versions kivyforge targets satisfies.
#
# ``PYTHONDONTWRITEBYTECODE`` stops a launch writing into the artifact it was
# launched from. The reason is not macOS's — Linux seals nothing — it is that an
# AppDir is a real, writable directory in two of the three shapes kivyforge
# produces, and one of those is the tree the T3 checks inspect. Measured on
# dice-roller: launching a ``package -f folder`` AppDir deposited 75 ``.pyc``
# under ``usr/python``, and launching an unstripped ``build`` deposited 209, of
# which 100 landed in the payload itself. Inside a ``.AppImage`` nothing lands —
# the squashfs mounts ``ro``, so there this only stops the interpreter
# attempting writes that cannot succeed.
#
# This used to carry a real cost: the embedded stdlib shipped as source, so
# suppressing the cache made every launch pay the full parse. **The build now
# byte-compiles the staged stdlib** (roadmap item 9), so the artifact arrives
# with its ``__pycache__`` already in place and this variable is belt-and-braces
# — it stops a launch writing *anything* back, rather than being the reason
# launches were slow. The folder form used to buy speed by mutating itself,
# which is not a trade worth keeping; the AppImage could never buy it at all.
_APPRUN = """\
#!/bin/sh
# Generated by kivyforge — do not edit.
HERE="$(dirname "$(readlink -f "$0")")"

export PYTHONHOME="$HERE/usr/python"
export PYTHONPATH="$HERE/usr/app:$HERE/usr/lib"
export PYTHONNOUSERSITE=1
# Keep imports from writing __pycache__ back into the AppDir: the folder form is
# writable, and it is also what the T3 checks inspect. A no-op inside a mounted
# .AppImage, which is read-only anyway.
export PYTHONDONTWRITEBYTECODE=1
{native_block}
# Match the window's WM_CLASS to the .desktop StartupWMClass so the app groups
# under its own icon on both X11 and Wayland.
export SDL_VIDEO_X11_WMCLASS="{app_id}"
export SDL_VIDEO_WAYLAND_WMCLASS="{app_id}"

exec "$HERE/usr/python/bin/python3" -P -m {entry} "$@"
"""

# Only emitted when the app declares native binaries (no dead env vars
# otherwise — symmetry with the "no empty bin/" rule). PATH is prepended so a
# bundled helper wins by name; LD_LIBRARY_PATH is appended so the host's and the
# wheels' auditwheel-vendored .so's still win the search and a declared lib is
# only a last resort (decided Option B, linux-spec).
_NATIVE_BINARIES_BLOCK = """
# Declared native binaries (see linux-spec): helpers by name, libs by soname.
export PATH="$HERE/usr/bin:$PATH"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$HERE/usr/bin"
"""


def entry_point_rel_path(entry_point: str) -> str:
    """Map a (possibly dotted) ``entry_point`` to its ``/``-joined module path.

    ``"main"`` -> ``"main"``; ``"pkg.start"`` -> ``"pkg/start"`` (i.e.
    ``usr/app/pkg/start.py``), matching the ``app_dir``/``entry_point`` layout
    contract in the shared pyproject spec.
    """
    return "/".join(entry_point.split("."))


def render_apprun(
    *, entry_point: str, app_id: str, has_native_binaries: bool = False
) -> str:
    """The ``AppRun`` shell source for *entry_point* + *app_id* (pure/testable).

    *entry_point* may be a dotted module name (e.g. ``pkg.start``); each segment
    must be a valid, non-keyword Python identifier. When *has_native_binaries*
    is set, ``usr/bin`` is prepended to ``PATH`` and appended to
    ``LD_LIBRARY_PATH``; otherwise the block is omitted entirely.
    """
    parts = entry_point.split(".")
    if not entry_point or not all(
        p.isidentifier() and not keyword.iskeyword(p) for p in parts
    ):
        raise AppDirError(f"entry_point {entry_point!r} is not a valid module name.")
    native_block = _NATIVE_BINARIES_BLOCK if has_native_binaries else ""
    return _APPRUN.format(
        entry=entry_point,
        app_id=app_id,
        native_block=native_block,
    )


def build_apprun(
    dest: Path, *, entry_point: str, app_id: str, has_native_binaries: bool = False
) -> None:
    """Write an executable ``AppRun`` at *dest*."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        render_apprun(
            entry_point=entry_point,
            app_id=app_id,
            has_native_binaries=has_native_binaries,
        ),
        "utf-8",
    )
    dest.chmod(0o755)
