"""Bootstrap generation + launcher placement (host-agnostic)."""

from __future__ import annotations

import pytest

from kivyforge.platforms.windows import WindowsBundleError
from kivyforge.platforms.windows import launcher as L
from kivyforge.platforms.windows.launcher import (
    launcher_exe_name,
    place_launcher,
    render_bootstrap,
    write_bootstrap,
)
from kivyforge.platforms.windows.rcedit import ResourcePatch


class TestRenderBootstrap:
    def test_bakes_app_id_and_entry(self):
        src = render_bootstrap(entry_point="pkg.main", app_id="Acme.App")
        assert "_APP_ID = 'Acme.App'" in src
        assert "_ENTRY = 'pkg.main'" in src

    def test_sets_app_id_before_window(self):
        src = render_bootstrap(entry_point="main", app_id="A.B")
        assert "SetCurrentProcessExplicitAppUserModelID" in src
        # _set_app_id runs before any DLL-dir registration inside _bootstrap.
        body = src.split("def _bootstrap():", 1)[1]
        assert body.index("_set_app_id") < body.index("_register_dll_dir")

    def test_discovers_share_generically(self):
        src = render_bootstrap(entry_point="main", app_id="A.B")
        assert '"python" / "share"' in src
        assert "sdl2" not in src.lower()  # not hard-coded to any dep

    def test_retains_dll_cookies(self):
        src = render_bootstrap(entry_point="main", app_id="A.B")
        assert "_DLL_DIR_COOKIES" in src
        assert "_DLL_DIR_COOKIES.append(os.add_dll_directory" in src

    def test_imports_not_run_as_main(self):
        src = render_bootstrap(entry_point="main", app_id="A.B")
        assert "importlib.import_module(_ENTRY)" in src

    def test_registers_native_bin(self):
        src = render_bootstrap(entry_point="main", app_id="A.B")
        assert '_BUNDLE / "bin"' in src

    @pytest.mark.parametrize("bad", ["", "1abc", "pkg.", "def", "a-b", "pkg..x"])
    def test_rejects_bad_entry_point(self, bad):
        with pytest.raises(WindowsBundleError, match="not a valid module name"):
            render_bootstrap(entry_point=bad, app_id="A.B")

    def test_accepts_dotted_entry(self):
        assert render_bootstrap(entry_point="a.b.c", app_id="A.B")


class TestWriteBootstrap:
    def test_writes_fixed_name(self, tmp_path):
        dest = write_bootstrap(tmp_path, entry_point="main", app_id="A.B")
        assert dest.name == "_kivyforge_bootstrap.py"
        assert dest.read_text(encoding="utf-8").startswith("# Generated by kivyforge")


class TestLauncherExeName:
    @pytest.mark.parametrize(
        "display,expected",
        [
            ("My App", "My App.exe"),
            ("Bad:Name?", "Bad Name.exe"),
            ("CON", "CON_.exe"),
        ],
    )
    def test_safe_name(self, display, expected):
        assert launcher_exe_name(display) == expected


class TestPlaceLauncher:
    def test_copies_and_patches(self, tmp_path, monkeypatch):
        src = tmp_path / "vendored.exe"
        src.write_bytes(b"MZ-launcher")
        bundle = tmp_path / "bundle"
        bundle.mkdir()

        calls = {}

        def _fake_patch(exe, patch, *, rcedit=None):
            calls["exe"] = exe
            calls["patch"] = patch

        monkeypatch.setattr(L, "patch_resources", _fake_patch)
        placed = place_launcher(
            bundle,
            display_name="My App",
            patch=ResourcePatch(product_name="My App"),
            launcher_src=src,
        )
        assert placed == bundle / "My App.exe"
        assert placed.read_bytes() == b"MZ-launcher"
        assert calls["exe"] == placed
        assert calls["patch"].product_name == "My App"
