"""The AppDir ``AppRun`` launcher — a POSIX shell script (linux-spec).

AppImage does not require an ELF ``AppRun``, and Linux has no analog of the
Finder/LaunchServices problem that forced the compiled Mach-O stub on macOS, so
the launcher is a small shell script. It resolves its own directory (so the
AppDir stays relocatable), points the bundled CPython at its own home + the
app's ``lib``/``app`` directories, sets the SDL WM_CLASS so the window groups
under the ``.desktop``'s ``StartupWMClass``, and ``exec``s the interpreter on
the entry-point module.

There is deliberately **no ``LD_LIBRARY_PATH``**: PBS rpaths are
``$ORIGIN``-relative and manylinux wheels vendor their own native libs
(auditwheel), so the host's libGL/libEGL are found on the normal loader path.
"""

from __future__ import annotations

import keyword
from pathlib import Path

from . import AppDirError

# ``{entry}`` is a ``/``-joined module path (a dotted ``entry_point`` such as
# ``pkg.start`` maps to ``pkg/start``); ``{app_id}`` is a validated ``.desktop``
# basename (letters/digits/hyphen/period) — both safe to inline.
_APPRUN = """\
#!/bin/sh
# Generated by kivyforge — do not edit.
HERE="$(dirname "$(readlink -f "$0")")"

export PYTHONHOME="$HERE/usr/python"
export PYTHONPATH="$HERE/usr/app:$HERE/usr/lib"
export PYTHONNOUSERSITE=1

# Match the window's WM_CLASS to the .desktop StartupWMClass so the app groups
# under its own icon on both X11 and Wayland.
export SDL_VIDEO_X11_WMCLASS="{app_id}"
export SDL_VIDEO_WAYLAND_WMCLASS="{app_id}"

exec "$HERE/usr/python/bin/python3" "$HERE/usr/app/{entry}.py" "$@"
"""


def entry_point_rel_path(entry_point: str) -> str:
    """Map a (possibly dotted) ``entry_point`` to its ``/``-joined module path.

    ``"main"`` -> ``"main"``; ``"pkg.start"`` -> ``"pkg/start"`` (i.e.
    ``usr/app/pkg/start.py``), matching the ``app_dir``/``entry_point`` layout
    contract in the shared pyproject spec.
    """
    return "/".join(entry_point.split("."))


def render_apprun(*, entry_point: str, app_id: str) -> str:
    """The ``AppRun`` shell source for *entry_point* + *app_id* (pure/testable).

    *entry_point* may be a dotted module name (e.g. ``pkg.start``); each segment
    must be a valid, non-keyword Python identifier.
    """
    parts = entry_point.split(".")
    if not entry_point or not all(
        p.isidentifier() and not keyword.iskeyword(p) for p in parts
    ):
        raise AppDirError(f"entry_point {entry_point!r} is not a valid module name.")
    return _APPRUN.format(entry=entry_point_rel_path(entry_point), app_id=app_id)


def build_apprun(dest: Path, *, entry_point: str, app_id: str) -> None:
    """Write an executable ``AppRun`` at *dest*."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_apprun(entry_point=entry_point, app_id=app_id), "utf-8")
    dest.chmod(0o755)
