lock-version = "1.0"
created-by = "kivyforge"
requires-python = ">=3.14"
extras = []
dependency-groups = []
default-groups = []

[[packages]]
name = "filetype"
version = "1.2.0"

[[packages.wheels]]
name = "filetype-1.2.0-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/18/79/1b8fa1bb3568781e84c9200f951c735f3f157429f44be0495da55894d620/filetype-1.2.0-py2.py3-none-any.whl"
hashes = { sha256 = "7ce71b6880181241cf7ac8697a2f1eb6a8bd9b429f7ad6d27b8db9ba5f1c2d25" }

[[packages]]
name = "Kivy"
version = "3.0.0.dev202610051055"
requires-python = ">=3.11"
dependencies = [{ name = "Kivy-Garden" }, { name = "docutils" }, { name = "pygments" }, { name = "requests" }, { name = "filetype" }]

[packages.tool.kivyforge]
direct_requirement = true

[[packages.wheels]]
name = "kivy-3.0.0.dev202610051055-cp315-cp315-ios_13_0_arm64_iphoneos.whl"
url = "https://github.com/ElliotGarbus/kivy-mobile-wheels/releases/download/kivy-ios-3.0.0.dev202610051055/kivy-3.0.0.dev202610051055-cp315-cp315-ios_13_0_arm64_iphoneos.whl"
hashes = { sha256 = "2ab99cb2650b08272b014970754f55b0f62e20d3b1a406da1a06b5f2f14f8883" }

[[packages.wheels]]
name = "kivy-3.0.0.dev202610051055-cp315-cp315-ios_13_0_arm64_iphonesimulator.whl"
url = "https://github.com/ElliotGarbus/kivy-mobile-wheels/releases/download/kivy-ios-3.0.0.dev202610051055/kivy-3.0.0.dev202610051055-cp315-cp315-ios_13_0_arm64_iphonesimulator.whl"
hashes = { sha256 = "3bdeab7a91f6f0e0b480f57c9f9d9cefc3ca2808d2a4543d94a291d9379cd5a0" }

[[packages]]
name = "more-itertools"
version = "11.1.0"
requires-python = ">=3.10"

[packages.tool.kivyforge]
direct_requirement = true

[[packages.wheels]]
name = "more_itertools-11.1.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e8/3d/1087453384dbde46a8c7f9356eead2c58be8a7bf156bca40243377c85715/more_itertools-11.1.0-py3-none-any.whl"
hashes = { sha256 = "4b65538ae22f6fed0ce4874efd317463a7489796a0939fa66824dd542125a192" }

[tool.kivyforge]
schema_version = 1
kivyforge_version = "3.0.0.dev0"
generated_at = "2026-10-08T12:20:37Z"
pyproject_sha256 = "fc8dbced07c9fe739de7149481eff073d50466d51f91c2a50c57b42a040def88"
tool_kivyforge_schema_version = 1

[tool.kivyforge.python_xcframework]
version = "3.15.0b4"
url = "https://www.python.org/ftp/python/3.15.0/python-3.15.0b4-iOS-XCframework.tar.gz"
sha256 = "dbf1095502e0b4a0dc2a4d96ae1b1d92ee8c0b7bea773862f7124ede0017e3dc"
