lock-version = "1.0"
created-by = "kivyforge"
requires-python = ">=3.14"
extras = []
dependency-groups = []
default-groups = []

[tool.kivyforge]
schema_version = 1
kivyforge_version = "3.0.0.dev0"
generated_at = "2026-07-08T03:38:33Z"
pyproject_sha256 = "ff7e0bfdde061d2eda3d2bad792302123f4ae001261488a5b1693a26105f1046"
tool_kivyforge_schema_version = 1

[tool.kivyforge.python_xcframework]
version = "3.15.0b2"
url = "https://www.python.org/ftp/python/3.15.0/python-3.15.0b2-iOS-XCframework.tar.gz"
sha256 = "fd6b6fb8f82cf44622d28ea53b8197c89fb06505557d29d4d7a47f9386c1c896"
