"""The ``.app`` launcher — the desktop analog of the iOS ``main.m`` bootstrap.

A tiny POSIX shell script placed at ``Contents/MacOS/<executable>``. It resolves
the bundle relative to itself (so the ``.app`` is fully relocatable), points the
bundled CPython at its own home + the app's ``lib``/``app`` directories, then
execs the entry-point module. Kept as a script (not a compiled stub) so the
bundler needs no C compiler; the Mach-O binaries that *must* be signed live in
the runtime + wheels and are signed separately.
"""

from __future__ import annotations

from pathlib import Path

_TEMPLATE = """\
#!/bin/sh
# Generated by kivyforge — do not edit.
here=$(cd "$(dirname "$0")" && pwd)
contents=$(cd "$here/.." && pwd)
home="$contents/Resources/python"
app="$contents/Resources/app"
lib="$contents/Resources/lib"

export PYTHONHOME="$home"
export PYTHONPATH="$app:$lib${{PYTHONPATH:+:$PYTHONPATH}}"
# Isolate from the user's ~/.local and site config; the bundle is self-contained.
export PYTHONNOUSERSITE=1

cd "$app"
exec "$home/bin/python3" "$app/{entry}.py" "$@"
"""


def write_launcher(path: Path, *, entry_point: str) -> None:
    """Write the executable launcher script for *entry_point* to *path*."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_TEMPLATE.format(entry=entry_point), encoding="utf-8")
    path.chmod(0o755)
